# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -andrejjsigachev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

services:
  - postgresql
addons:
  postgresql: "11.5"


env:
  global:
    - CODECOV_TOKEN="ab1b20f3-cf01-4aac-b153-4ecd884e2999"